= DefuseMe Library for Arduino =

This library allows an Arduino NANO to connect to bombs Raspberry Pi and contorl LEDs, buttons and switches.

clone this into your arduino `libraries` folder.

You can find examples in the `examples` folder:

 - `project_b` very simple demo (talking to the core library directly)
 - `StateMachineDemo` demo using the StateMachine and PushButton/DebounceInput classes
 - `defuseMeBatteries1.5V` counts the number of ~1.5V batteries in the battery holder and reports them on startup (triggers if someone removes/adds a battery)
 - `defuseMeSerialStatic` static serial number module

== License ==

Copyright (c) Arduino LLC. All right reserved.

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 2.1 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with this library; if not, write to the Free Software
Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
